env:
  global:
    - CC_TEST_REPORTER_ID=01bac0f4a284bbc69bd4921ee76d5262434c5944ca5439f454311350f4b7aa88

language: php

php:
  - '7.2'

install:
  - make install

script:
  - make lint
  - make test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
